services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION}
    container_name: ${N8N_CONTAINER_NAME}
    networks:
      - shared-net
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      TZ: ${N8N_TIMEZONE}
      GENERIC_TIMEZONE: ${N8N_TIMEZONE}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_PROXY_HOPS: ${N8N_PROXY_HOPS}
      WEBHOOK_URL: https://${N8N_SUBDOMAIN:-n8n}.${STACK_DOMAIN:-localhost}/
    restart: unless-stopped

networks:
  shared-net:
    external: true

volumes:
  n8n_data:
