networks:
  shared-net:
    name: shared-net
    driver: bridge

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    networks:
      - shared-net
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    networks:
      - shared-net
    restart: unless-stopped

volumes:
  mariadb_data:
